### ISSUE TITLE
Transaction stays in "pending" status after using Express Checkout

### ISSUE THREAD

**Issue by vkoudela** [reactioncommerce/reaction-paypal#14] opened 2015-07-29 15:02 UTC
After making payment using Express Checkout, money is taken from buyer's account, but transaction stays in "pending" status on PayPal, regarding that order has been completed by administrator. When administrator clicks on "Complete payment" button, additional API request should probably be fired to actually complete the payment on PayPal side.

I tested this case on currently latest commit in dev branch (ff7d800).

Here's the screenshot from sandbox.paypal.com that shows the payment in pending status. This bug prevents the transactions to be refunded.
![screen shot 2015-07-29 at 16 51 39](https://cloud.githubusercontent.com/assets/702123/8961003/04ce7e7e-3613-11e5-9829-363b39ca5a5c.png)

**Comment by aaronjudd** [comment] 2015-11-17 22:08
this needs review to see if we can still replicate this.  Might have  been closed by @mikemurray in https://github.com/reactioncommerce/reaction-paypal/pull/18

**Comment by boboci9** [comment] 2015-11-18 10:10
I made some orders yesterday and I still get the pending status for the transactions with the new version.

**Comment by zenweasel** [comment] 2015-11-25 00:37
@aaronjudd , @boboci9 Are there steps to reproduce this error?

**Comment by boboci9** [comment] 2015-11-25 18:53
I just make a payment with Express checkout using sandbox and the transaction remains pending.

**Comment by zenweasel** [comment] 2015-11-26 01:36
I have verified that after being placed the order is still in "Pending". I don't see a "Capture Payment" button like Paypal Pro and Stripe have which seems to be the missing element here.

**Closed** 2015-12-08 07:36 UTC
Labels: bug

**Comment by boboci9** [comment] 2015-12-09 14:37
Hi, I just tried making a payment with the new version and I still get:
```
 {
                "processor" : "PaypalExpress",
                "method" : "Paypal Express Checkout",
                "transactionId" : "3FC8...",
                "amount" : 39.95,
                "status" : "created",
                "mode" : "authorize",
                "createdAt" : ISODate("2015-12-09T14:31:46.000Z"),
                "updatedAt" : ISODate("2015-12-09T14:31:46.000Z"),
                "transactions" : [ 
                    {
                        "TOKEN" : "EC-...",
                        "TIMESTAMP" : "2015-12-09T14:31:46Z",
                        "CORRELATIONID" : "70141e03959aa",
                        "ACK" : "Success",
                        "VERSION" : "52.0",
                        "BUILD" : "18308778",
                        "TRANSACTIONID" : "3FC....",
                        "TRANSACTIONTYPE" : "expresscheckout",
                        "PAYMENTTYPE" : "instant",
                        "ORDERTIME" : "2015-12-09T14:31:46Z",
                        "AMT" : "39.95",
                        "TAXAMT" : "0.00",
                        "CURRENCYCODE" : "USD",
                        "PAYMENTSTATUS" : "Pending",
                        "PENDINGREASON" : "authorization",
                        "REASONCODE" : "None"
                    }
                ]
            }
```
Is there anything else I have to check to have a finalized transaction?
Thanks in advance.

**Comment by zenweasel** [comment] 2015-12-10 00:02
@boboci9 Yes. Go into the orders dashboard and select that individual order. Click on "Approve" and then click on "Capture Payment". That will capture the payment and move the order to "Completed"

**Comment by boboci9** [comment] 2015-12-10 07:06
Thanks, I will test that out and report back.

**Comment by boboci9** [comment] 2016-01-20 09:44
@zenweasel I was wondering why do you need to capture the payment by the admin, at one point when there will be many orders the admin won't go one by one and approve the payment, isn't there any solution when the payment can be approved by paypal without the admin's approval?

**Comment by zenweasel** [comment] 2016-01-20 10:11
@boboci9 I was just making Paypal consistent with the way the other packages work. Are you talking about doing `authorize` and `capture` in one step. A lot of stores that ship physical goods need to separate these steps so that a `capture` is only done when the actual goods are shipped. So making this one step is definitely not going to work for everybody. I did foresee a time when we could make this configurable so that you could make the first step `authorize and capture`.

**Comment by boboci9** [comment] 2016-01-20 12:06
Actually in our requirements the admin doesn't want to approve the payment they want this step to be done automatically so I need a way to check if the payment is still pending or it already went through paypal's perspective and I need to set it completed automatically. I was wondering if you could point me in the right direction since you worked on the approve and capture steps.

**Comment by zenweasel** [comment] 2016-01-20 12:22
So just to clarify, do you want `authorize` and `capture` to be called when the `submitPaypal` method is called at checkout?

**Comment by zenweasel** [comment] 2016-01-20 12:24
The approve step actually does nothing with the Payment Method AKAIK. Only capture.

**Comment by boboci9** [comment] 2016-01-20 13:38
Yes, I want to check with paypal if the transaction is complete, and authorize it automatically at checkout, so the admin doesn't have to check if the payment was complete or not.

**Comment by zenweasel** [comment] 2016-01-20 22:40
So in most Payment systems there are two stages:
`authorize` - Which verifies that the funds are available and "reserves" the funds but no funds are actually transferred. You can usually cancel an authorization with no problem and an authorization usually expires after a short period of time. In the US at least there are strict laws about how long you have to ship a product if you actually take the money (typically 24 hours), whereas an authorization has no such liability. This reduces the risk of chargebacks which is a huge deal (from my experience)

`capture` - actually transfers the money from the customer and can only be undone with a refund.

So what I am thinking you want to do is do both `authorize` and `capture` both at time of checkout in one step. Is that correct? If so PM me on Gitter and I can see how I can help you get that accomplished. I think it should be trivial to do.

**Comment by zenweasel** [comment] 2016-01-20 22:45
I am thinking you probably aren't the only person who would want this so if we can make it configurable we could push the changes into the repo.

**Comment by aaronjudd** [comment] 2016-01-20 22:53
It's not really the "recommended" process, but it's pretty common to want to just use 'capture' and not auth, and some processors charge for both approvals, so in a high volume operation it may make sense to combine them.  "Auth before Trans" would be a good option, but agree that it needs to be configurable in the UI as well.

**Comment by zenweasel** [comment] 2016-01-20 22:54
I think most of the `authorize` methods take a "transactionType" parameter meant to allow that. Should I open a new ticket for this as an enhancement?

**Comment by aaronjudd** [comment] 2016-01-20 22:55
yes, new ticket (and yeah, that was the thinking)..

**Comment by boboci9** [comment] 2016-01-21 12:39
@zenweasel calling the authorize and capture methods at checkout would be one way to go, but I was researching if there is any other way offered by paypal to implement straight orders that don't need these two additional steps, but I couldn't find anything in their documentations so far.
